var keyMirror = require('keyMirror');

module.exports = keyMirror({
	SEARCH_NAME_SUCCESS: 'SEARCH_NAME_SUCCESS',
	SEARCH_NAME_FAILURE: 'SEARCH_NAME_FAILURE',
	SEARCH_ZIP_SUCCESS: 'SEARCH_ZIP_SUCCESS',
	SEARCH_ZIP_FAILURE: 'SEARCH_ZIP_FAILURE'
});